networks:
  default:
    name: dezibot-network

services:
  dezibotdebuginterface.api:
    image: dezibotdebuginterface.api:latest
    container_name: dezibotdebuginterface.api
    build:
      context: .
      dockerfile: backend/DezibotDebugInterface.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CORS_ALLOWED_ORIGIN: http://dezibotdebuginterface.web:3000
    ports:
      - "5160:8080"
    networks:
      - default

  dezibotdebuginterface.web:
    image: dezibotdebuginterface.web:latest
    container_name: dezibotdebuginterface.web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://dezibotdebuginterface.api:8080 # TODO: Fix CORS for production
    ports:
      - "3000:3000"
    networks:
      - default
    depends_on:
      - dezibotdebuginterface.api
