networks: # Define a network to allow the containers to communicate with each other using their service names
  default:
    name: dezibot-network

services:
  dezibotdebuginterface.api:
    image: dezibotdebuginterface.api:latest
    container_name: dezibotdebuginterface.api
    build:
      context: .
      dockerfile: backend/DezibotDebugInterface.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CORS_ALLOWED_ORIGIN: http://dezibotdebuginterface.frontend:3000
    ports:
      - "5160:8080"
    networks:
      - default

  dezibotdebuginterface.web:
    image: dezibotdebuginterface.web:latest
    container_name: dezibotdebuginterface.web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://dezibotdebuginterface.api:8080
    depends_on:
      - dezibotdebuginterface.api
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevent overwriting node_modules in the container
    networks:
      - default
