services:
  dezibotdebuginterface.api:
    image: dezibotdebuginterface.api:latest
    container_name: dezibotdebuginterface.api
    build:
      context: .
      dockerfile: backend/DezibotDebugInterface.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5160:8080"
