networks:
  default:
    name: dezibot-network

services:
  dezibotdebuginterface.api:
    image: dezibotdebuginterface.api:latest
    container_name: dezibotdebuginterface.api
    build:
      context: .
      dockerfile: backend/DezibotDebugInterface.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5160:8080"
    networks:
      - default

  dezibotdebuginterface.web:
    image: dezibotdebuginterface.web:latest
    container_name: dezibotdebuginterface.web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NUXT_INTERNAL_SERVER_URL=http://dezibotdebuginterface.api:8080 # works only in docker-compose for http requests from the nuxt server to the api
      - NUXT_PUBLIC_SERVER_URL=http://localhost:5160  # Can be an ip address, is used when outside of docker e.g. in the browser
    ports:
      - "3000:3000"
    networks:
      - default
    depends_on:
      - dezibotdebuginterface.api
