networks: # Define a network to allow the containers to communicate with each other using their service names
  default:
    name: dezibot-network

services:
  dezibotdebuginterfaceapi:
    image: dezibotdebuginterfaceapi:latest
    container_name: dezibotdebuginterface.api
    build:
      context: .
      dockerfile: backend/DezibotDebugInterface.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CORS_ALLOWED_ORIGIN: http://dezibotdebuginterface.web:3000
    ports:
      - "5160:8080"
    networks:
      - default

  # dezibotdebuginterface.frontend:
  #   image: dezibotdebuginterfaceweb:latest
  #   container_name: dezibotdebuginterface.web
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #     - DEZIBOT_HUB=http://dezibotdebuginterfaceapi:8080/dezibot-hub # Websocket connection to the backend
  #   depends_on:
  #     - dezibotdebuginterfaceapi
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules # Prevent overwriting node_modules in the container
  #   networks:
  #     - default
